---
- name: apt packages update
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: upgrade packages
  become: true
  apt:
    upgrade: yes
    
- name: Remove dependencies no longer required
  become: true
  apt:
    autoremove: yes

- name: Install Node.js 13/dep
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest

